spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 7huetsst981ca38kevnkctfc0dp3fsei.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email

          naver:
            client-id: 5GFPAEsWnCuPHEfpNez4
            client-secret: x98mI6s5I0
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            scope:
              - name
              - email
              - profile_image
            client-name: Naver

          kakao:
            client-id: abd735e852005072d69c7c4050d2afda
            client-secret: 9EpJPhw7Pl0KkKdVQZXdKHPa35zPCmve
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - profile_image
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            client-name: Kakao

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-info-authentication-method: header
            user-name-attribute: response

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-info-authentication-method: header
            user-name-attribute: id


